### ISSUE TITLE
Not easy to use for starters

### ISSUE THREAD

**Issue by probonopd** [uit-no/nsroot#2]
Hello, thanks for the `nsroot` tool and for mentioning [AppImage](http://appimage.org/).

It would be nice if it would be a bit more user friendly out-of-the box. E.g., most users will try to launch it like so:

```
$ ./nsroot 
Error: execvp failed (errno: 2): No such file or directory
```

It tries to execute somehting, but it is unclear what that is and why it fails. The help says:

```
Usage: ./nsroot [OPTION] NEWROOT [COMMAND [ARG]...]
   or: ./nsroot [OPTION]
(...)
If no COMMAND is given, run '${SHELL} -i' (default: '/bin/bash -i')
```

but that doesn't seem to be the case, at least not without an `OPTION`:

```
clone(strace: Process 3388 attached
child_stack=0x703270, flags=CLONE_NEWNS|CLONE_NEWUSER|SIGCHLD) = 3388
[pid  3388] getpid()                    = 3388
[pid  3388] close(4 <unfinished ...>
[pid  3387] close(4 <unfinished ...>
[pid  3388] <... close resumed> )       = 0
[pid  3387] <... close resumed> )       = 0
[pid  3388] read(3,  <unfinished ...>
[pid  3387] wait4(3388,  <unfinished ...>
[pid  3388] <... read resumed> "", 1)   = 0
[pid  3388] getcwd("/home/me/nsroot-master", 4096) = 23
[pid  3388] chroot("/home/me/nsroot-master") = 0
[pid  3388] chdir("/")                  = 0
[pid  3388] execve("/bin/bash", ["/bin/bash", "-i"], [/* 16 vars */]) = -1 ENOENT (No such file or directory)
[pid  3388] write(2, "Error: execvp failed (errno: 2):"..., 59Error: execvp failed (errno: 2): No such file or directory
```

Everything I try is not successful:

```
$ ./nsroot -v /bin:/bin
Error: pivot_root failed (errno: 2): No such file or directory
$ ./nsroot -v /bin:/bin /bin/bash
Error: pivot_root failed (errno: 20): Not a directory
$ ./nsroot -v /:/ /bin:/bin /bin/bash
Error: resolving new root directory failed (errno: 2): No such file or directory
```

**Comment by iaraknes** [comment]
Hello, thanks for the feedback.

I apologize that there was no README included in the first release. The reason the commands in your description doesn't work is that they use the current working directory as the new root (/) directory.

I just committed a README.md and I also included some examples for how to get started. I hope this makes it more obvious.

Please let me know if you still run into issues.
